---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build-and-lint
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - curl -s https://get.yaml.sh | sh
  - export NAME=`ysh -f ./chart/Chart.yaml -Q "name"`
  - export VERSION=`ysh -f ./chart/Chart.yaml -Q "version"`
  - mv chart $NAME
  - helm init -c
  - helm lint $NAME
  - wget -O - https://github.com/norwoodj/helm-docs/releases/download/v0.9.0/helm-docs_0.9.0_Linux_x86_64.tar.gz | tar xvzf - helm-docs
  - ./helm-docs
  - helm package $NAME
  - git config --global user.email "drone@holthome.net"
  - git config --global user.name "Drone.IO"
  - git config --global push.default simple
  - git tag -a -m 'v$VERSION' v$VERSION
  - git remote add tags $DRONE_REPO_LINK
  - git push tags v$VERSION
  - git remote remove tags

- name: clone_gh-pages
  image: plugins/git
  commands:
  - git clone -b gh-pages https://github.com/blazure/helm-charts

- name: build
  image: dtzar/helm-kubectl:2.16.1
  commands:
  - helm init -c
  - mv ${name}*.tgz helm-charts
  - helm repo index --url https://charts.blazure.com ./helm-charts

- name: push_gh-pages
  image: appleboy/drone-git-push
  settings:
    remote: https://github.com/blazure/helm-charts.git
    branch: gh-pages
    local_branch: gh-pages
    commit: true
    force: true
    author_name: "[Automated] Drone.IO"
    author_email: "drone@holthome.net"
    commit_message: "Updated Packages"
    path: helm-charts

trigger:
  branch:
  - master
  event:
    include:
    - push
